#!/bin/bash 


#HealtCheck for NSOPORTE Fop2 Container
/bin/nc -z 127.0.0.1 4445
FOP2=$?
DB=0
AST=0

if [ "$NSPBX" != "" ];then
	/bin/nc -z $NSPBX 3306
	DB=$?

	/bin/nc -z $NSPBX 5038
	AST=$?
fi



if [ "$FOP2" != "0" ] || [ "$DB" != "0" ] || [ "$AST" != "0" ];then
	exit 1

fi 


exit 0