#!/bin/bash


#There are two Env Strings pased by container 
#DBHOST = Mysql host
#ASTHOST = Asterisk port 

if [ "$DBHOST" = "" ];then
	DBHOST=127.0.0.1
fi


if [ "$ASTHOST" = "" ];then 
	ASTHOST=127.0.0.1
fi


if [ "$DBPORT" = "" ];then 
	DBPORT=3306
fi

if [ "$ASTPORT" = "" ];then 
	ASTPORT=5038
fi


#If Env NSPBX defined then check Mariadb and asterisk services before start 
DB=2
AST=2

#Keep until mysql or asterisk Gets ready 
while [[ "$DB" -ne 0 ]] || [[ "$AST" -ne 0 ]];do

	/bin/nc -z $DBHOST $DBPORT
	DB=$?

	/bin/nc -z $ASTHOST $ASTPORT
	AST=$?

	echo "Waiting for Asterisk and Mysql get Ready!"
	sleep 3

done

echo "NSPBX Services Ready!"




#Check if activation code is given and active it
#if [ "$CODE" != "" ];then 

#	/usr/local/fop2/fop2_server --register --code $CODE

#fi 

#Starting Fop2 Service 
/usr/local/fop2/fop2_server -d -p /var/run/fop2.pid


if [ $? = 0 ]; then
	exec /usr/sbin/apachectl -D FOREGROUND

				else
	echo "Error on Fop2 Server...."
	exit 1
fi


